import paramiko
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect(hostname='46.235.8.120', port=22667, username='root', password='XM2KZ51f6aj7tNl', timeout=15, look_for_keys=False, allow_agent=False)
stdin, stdout, stderr = client.exec_command("find /opt/pz-server -name '*.jar' -type f 2>/dev/null")
stdin.close()
out = stdout.read().decode().strip()
print('JAR files:')
print(out)
stdin2, stdout2, stderr2 = client.exec_command("ls -la /opt/pz-server/")
stdin2.close()
out2 = stdout2.read().decode().strip()
print('\nPZ Server dir:')
print(out2[:3000])
client.close()
